In [1]:
import src.shur_decomposition as shd
import numpy as np
import matplotlib.pyplot as plt

### Решение задачи для блока $2 \times 2$:

In [2]:
A = np.array([[2, -5], [2, 3]])

shd.two_block_solution(A)

[(2.5, -3.122498999199199), (2.5, 3.122498999199199)]

### Проверка работы преобразования Хаусхолдера:

In [3]:
v = np.random.random(6)
print(v)
print((shd.householder(v) @ v).round(5))

[0.39794316 0.43973054 0.4115049  0.54023021 0.46748622 0.42080567]
[-1.09933  0.       0.       0.       0.       0.     ]


### Приведение матрицы к верхне-хейссенберговой форме:

In [7]:
A = np.random.random((6, 6))
print(A.round(4))

[[0.1857 0.6747 0.275  0.5805 0.6581 0.6884]
 [0.8995 0.8908 0.5312 0.3898 0.5908 0.2528]
 [0.7847 0.5055 0.9419 0.4026 0.887  0.497 ]
 [0.1515 0.6061 0.0883 0.4496 0.0522 0.1978]
 [0.1767 0.4253 0.1422 0.3281 0.4778 0.9788]
 [0.7658 0.8174 0.8077 0.0715 0.6758 0.7253]]


In [8]:
Q, R = shd.heissenberg(A)

In [9]:
print((Q.T @ Q).round(4))

[[ 1.  0.  0.  0.  0.  0.]
 [ 0.  1. -0. -0. -0. -0.]
 [ 0. -0.  1. -0. -0. -0.]
 [ 0. -0. -0.  1. -0. -0.]
 [ 0. -0. -0. -0.  1. -0.]
 [ 0. -0. -0. -0. -0.  1.]]


In [10]:
print((Q @ R - A).round(4))

[[ 0.  0.  0.  0.  0.  0.]
 [-0. -0. -0. -0. -0. -0.]
 [ 0.  0. -0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0. -0.]
 [ 0. -0.  0.  0.  0.  0.]
 [ 0.  0.  0. -0. -0. -0.]]


In [11]:
print(R.round(4))

[[ 0.1857  0.6747  0.275   0.5805  0.6581  0.6884]
 [-1.4372 -1.3853 -1.304  -0.5896 -1.2784 -0.9573]
 [-0.      0.5886 -0.1406  0.3474 -0.0154  0.4747]
 [ 0.     -0.     -0.3602 -0.0289 -0.2737 -0.4538]
 [ 0.     -0.     -0.     -0.3998 -0.1492 -0.0454]
 [-0.     -0.      0.      0.      0.303   0.6961]]


### Проверка поворота Гивенца:

In [15]:
G = shd.givenc(R[0:2, 0])

R[0:2, 0] = G @ R[0:2, 0]

print(R.round(4))

[[ 1.3246  0.2854  0.8578  0.0872  0.3509  0.7817]
 [-0.     -0.7735 -0.9021 -1.0644 -0.8633 -1.3597]
 [-0.      0.6857  0.3351  0.762   0.0796 -0.0781]
 [-0.      0.      0.8399  0.2721  0.3161  0.3631]
 [ 0.     -0.     -0.     -0.1267 -0.1181 -0.1278]
 [-0.     -0.      0.      0.     -0.0022 -0.3007]]


In [16]:
A = np.random.random((6, 6))
Q_1, R = shd.heissenberg(A)
Q_2, S = shd.top_qr(R)

print((Q_1 @ Q_2 @ S - A).round(4))

[[ 0.  0.  0.  0. -0.  0.]
 [-0. -0. -0. -0. -0. -0.]
 [-0. -0.  0.  0.  0.  0.]
 [-0.  0.  0.  0.  0.  0.]
 [-0. -0. -0. -0. -0. -0.]
 [-0. -0.  0.  0. -0. -0.]]


In [17]:
print(S.round(4))

[[ 0.9634  0.6564  0.7776  0.5952  0.7988  1.2602]
 [-0.      0.6064  0.3573  0.514   0.5875  0.6744]
 [ 0.     -0.      0.5038  0.5302  0.1189 -0.1276]
 [-0.     -0.      0.      0.6213  0.1445  0.1349]
 [-0.     -0.      0.      0.      0.1526 -0.3421]
 [-0.     -0.      0.     -0.      0.      0.5727]]


In [2]:
A = np.random.random((4, 4))

In [3]:
print(shd.naive_shur(A.T@ A, 20).round(4))

4.453619101457064e-17
8.910099070740402e-16
8.881940896714181e-16
5.568877045553501e-17
8.882094438160109e-16
5.611770291945971e-17
5.595155545630568e-17
1.1128034764013775e-16
1.9394798101144822e-18
5.597844067718301e-17
5.600531301748203e-17
5.611770117910161e-17
0.0
0.0
4.0389678347315804e-28
0.0
0.0
1.5777218104420236e-30
0.0
2.6963019221421302e-33
[[ 4.6098e+00 -0.0000e+00  3.3000e-03  1.0700e-02]
 [-0.0000e+00  3.2260e-01 -0.0000e+00 -5.2000e-03]
 [ 3.3000e-03 -0.0000e+00  4.0700e-02  0.0000e+00]
 [ 1.0700e-02 -5.2000e-03 -0.0000e+00  8.0000e-03]]


In [4]:
print(np.linalg.eig(A.T@A)[0].round(10))

[4.60979127 0.32268641 0.04069159 0.00784408]


In [19]:
A = np.random.random((6, 6))

In [20]:
(shd.hessenberg(A.T@A))[1].round(5)

array([[ 0.64479,  0.88292,  1.20537,  0.69659,  0.80319,  0.96101],
       [-2.07035, -3.90363, -6.04487, -3.00227, -4.24421, -5.13316],
       [ 0.     ,  0.48813,  0.09103, -0.32362,  0.10258,  0.31827],
       [-0.     , -0.     ,  0.56737,  0.14766,  0.69647, -0.03437],
       [-0.     , -0.     , -0.     ,  0.35706, -0.40178,  0.81099],
       [ 0.     ,  0.     , -0.     ,  0.     ,  0.15837, -0.03667]])

In [1]:
import src.shur_decomposition as shd
import numpy as np
import matplotlib.pyplot as plt

In [14]:
A = np.random.random((300,300))

In [15]:
sorted(np.linalg.eig(A.T@A)[0])

[4.851477030888322e-05,
 0.0005644029150939008,
 0.0018275302752360219,
 0.0048944411634278566,
 0.007448029601138548,
 0.016156712678298636,
 0.01957693561798772,
 0.03713326161901196,
 0.0475061399777154,
 0.055795593759904276,
 0.06560197750788656,
 0.06815478641604704,
 0.08064909697120959,
 0.1051333640173287,
 0.11887926857674949,
 0.13446944628372007,
 0.15229661506681555,
 0.17656176353559053,
 0.21591260537388784,
 0.25145133153488597,
 0.2743422611282685,
 0.299919136584807,
 0.31943019323609145,
 0.3806932110077213,
 0.3981564091826365,
 0.42416019525205795,
 0.43955709741633114,
 0.46865587690554117,
 0.48974650654736185,
 0.53804677273866,
 0.6138498876774944,
 0.6630110449217578,
 0.6942528122335784,
 0.720277650346789,
 0.7993021145711022,
 0.8345099182816232,
 0.9773844203084925,
 0.9880066453695163,
 0.99951960378841,
 1.0332762111894174,
 1.1058065249978615,
 1.1817382910768415,
 1.2999883218465877,
 1.3129794441687919,
 1.3842399050733079,
 1.4592367356406712,
 1.506

In [16]:
shd.eigenvalues(A.T@A, 1e-12, "naive")

num iterations: 6625


array([2.24270692e+04+0.j, 9.58675481e+01+0.j, 9.47391156e+01+0.j,
       9.33066398e+01+0.j, 9.02663557e+01+0.j, 8.89193999e+01+0.j,
       8.73764893e+01+0.j, 8.60422618e+01+0.j, 8.45503918e+01+0.j,
       8.32287804e+01+0.j, 8.22378070e+01+0.j, 8.10473225e+01+0.j,
       7.99575501e+01+0.j, 7.93902040e+01+0.j, 7.80295059e+01+0.j,
       7.74602735e+01+0.j, 7.64434573e+01+0.j, 7.49954569e+01+0.j,
       7.37555835e+01+0.j, 7.35385729e+01+0.j, 7.25932990e+01+0.j,
       7.16750741e+01+0.j, 7.11426769e+01+0.j, 7.08937934e+01+0.j,
       7.05824084e+01+0.j, 6.89417444e+01+0.j, 6.83874215e+01+0.j,
       6.83447786e+01+0.j, 6.68640376e+01+0.j, 6.61777897e+01+0.j,
       6.52755241e+01+0.j, 6.44188243e+01+0.j, 6.41759734e+01+0.j,
       6.38410071e+01+0.j, 6.15430117e+01+0.j, 6.14068254e+01+0.j,
       6.10335301e+01+0.j, 6.03511806e+01+0.j, 6.01048192e+01+0.j,
       5.89114610e+01+0.j, 5.85215699e+01+0.j, 5.78567817e+01+0.j,
       5.71238078e+01+0.j, 5.65057328e+01+0.j, 5.62146589e+01+

In [17]:
shd.eigenvalues(A.T@A, 1e-12, "simple")

num iterations: 6580


array([2.24270692e+04+0.j, 9.58675481e+01+0.j, 9.47391156e+01+0.j,
       9.33066398e+01+0.j, 9.02663557e+01+0.j, 8.89193999e+01+0.j,
       8.73764893e+01+0.j, 8.60422618e+01+0.j, 8.45503918e+01+0.j,
       8.32287804e+01+0.j, 8.22378070e+01+0.j, 8.10473225e+01+0.j,
       7.99575501e+01+0.j, 7.93902040e+01+0.j, 7.80295059e+01+0.j,
       7.74602735e+01+0.j, 7.64434573e+01+0.j, 7.49954569e+01+0.j,
       7.37555835e+01+0.j, 7.35385729e+01+0.j, 7.25932990e+01+0.j,
       7.16750741e+01+0.j, 7.11426769e+01+0.j, 7.08937934e+01+0.j,
       7.05824084e+01+0.j, 6.89417444e+01+0.j, 6.83874215e+01+0.j,
       6.83447786e+01+0.j, 6.68640376e+01+0.j, 6.61777897e+01+0.j,
       6.52755241e+01+0.j, 6.44188243e+01+0.j, 6.41759734e+01+0.j,
       6.38410071e+01+0.j, 6.15430117e+01+0.j, 6.14068254e+01+0.j,
       6.10335301e+01+0.j, 6.03511806e+01+0.j, 6.01048192e+01+0.j,
       5.89114610e+01+0.j, 5.85215699e+01+0.j, 5.78567817e+01+0.j,
       5.71238078e+01+0.j, 5.65057328e+01+0.j, 5.62146589e+01+

In [17]:
np.linalg.eig(A)

EigResult(eigenvalues=array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0.]), eigenvectors=array([[ 0.00000000e+000,  0.00000000e+000,  0.00000000e+000, ...,
         0.00000000e+000,  0.00000000e+000,  0.00000000e+000],
       [ 0.00000000e+000,  0.00000000e+000,  0.00000000e+000, ...,
         0.00000000e+000,  0.00000000e+000,  0.00000000e+000],
       [ 0.00000000e+000,  0.00000000e+000,  0.00000000e+000, ...,
         0.00000000e+000,  0.00000000e+000,  0.00000000e+000],
       ...,
       [ 0.00000000e+000,  5.21083774e-291, -5.21083774e-291, ...,
         5.21083774e-291, -5.21083774e-291,  0.00000000e+000],
       [ 1.00000000e+000, -1.00000000e+000,  1.00000000e+000, ...,
        -1.00000000e+000,  1.00000000e+000,  0.00000000e+000],
       [ 0.00000000e+000,  0.00000000e+000,  0.00000000e+000, ...

In [28]:
A = np.random.random((1000, 1000))

In [30]:
%timeit A[np.diag_indices_from(A[:50, :50])]

12.8 µs ± 44 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [22]:
np.diag_indices_from(A)

(array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]), array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]))

# Jacobi eigenvalue algorithm

In [2]:
from src.Jacobi_eig_algorithm import Jacobi_algorithm

In [3]:
n = 100

my_eigvals = np.random.randn(n)
L = np.diag(my_eigvals)
S = np.random.randn(n, n)
S, _ = np.linalg.qr(S)
A = S @ L @ S.T

In [4]:
D, J, off, num_cycles = Jacobi_algorithm(A, eigvals=False)
off, num_cycles

(1.668213519677723e-14, 9)

In [5]:
np.linalg.norm(np.sort(np.diag(D)) - np.sort(my_eigvals))

1.7433343950076163e-13